package funcs

import (
	"io/fs"

	"github.com/hashicorp/hcl/v2/ext/tryfunc"
	ctyyaml "github.com/zclconf/go-cty-yaml"
	"github.com/zclconf/go-cty/cty"
	"github.com/zclconf/go-cty/cty/function"
	"github.com/zclconf/go-cty/cty/function/stdlib"
)

// Functions returns the set of functions that should be used to when evaluating
// expressions in the receiving scope.
func Functions(target fs.FS, baseDir string) map[string]function.Function {
	return map[string]function.Function{
		"abs":              stdlib.AbsoluteFunc,
		"abspath":          AbsPathFunc,
		"alltrue":          AllTrueFunc,
		"anytrue":          AnyTrueFunc,
		"basename":         BasenameFunc,
		"base64decode":     Base64DecodeFunc,
		"base64encode":     Base64EncodeFunc,
		"base64gzip":       Base64GzipFunc,
		"base64sha256":     Base64Sha256Func,
		"base64sha512":     Base64Sha512Func,
		"bcrypt":           BcryptFunc,
		"can":              tryfunc.CanFunc,
		"ceil":             stdlib.CeilFunc,
		"chomp":            stdlib.ChompFunc,
		"cidrhost":         CidrHostFunc,
		"cidrnetmask":      CidrNetmaskFunc,
		"cidrsubnet":       CidrSubnetFunc,
		"cidrsubnets":      CidrSubnetsFunc,
		"coalesce":         CoalesceFunc,
		"coalescelist":     stdlib.CoalesceListFunc,
		"compact":          stdlib.CompactFunc,
		"concat":           stdlib.ConcatFunc,
		"contains":         stdlib.ContainsFunc,
		"csvdecode":        stdlib.CSVDecodeFunc,
		"dirname":          DirnameFunc,
		"distinct":         stdlib.DistinctFunc,
		"element":          stdlib.ElementFunc,
		"endswith":         EndsWithFunc,
		"chunklist":        stdlib.ChunklistFunc,
		"file":             MakeFileFunc(target, baseDir, false),
		"fileexists":       MakeFileExistsFunc(target, baseDir),
		"fileset":          MakeFileSetFunc(target, baseDir),
		"filebase64":       MakeFileFunc(target, baseDir, true),
		"filebase64sha256": MakeFileBase64Sha256Func(target, baseDir),
		"filebase64sha512": MakeFileBase64Sha512Func(target, baseDir),
		"filemd5":          MakeFileMd5Func(target, baseDir),
		"filesha1":         MakeFileSha1Func(target, baseDir),
		"filesha256":       MakeFileSha256Func(target, baseDir),
		"filesha512":       MakeFileSha512Func(target, baseDir),
		"flatten":          stdlib.FlattenFunc,
		"floor":            stdlib.FloorFunc,
		"format":           stdlib.FormatFunc,
		"formatdate":       stdlib.FormatDateFunc,
		"formatlist":       stdlib.FormatListFunc,
		"indent":           stdlib.IndentFunc,
		"index":            IndexFunc, // stdlib.IndexFunc is not compatible
		"join":             stdlib.JoinFunc,
		"jsondecode":       stdlib.JSONDecodeFunc,
		"jsonencode":       stdlib.JSONEncodeFunc,
		"keys":             stdlib.KeysFunc,
		"length":           LengthFunc,
		"list":             ListFunc,
		"log":              stdlib.LogFunc,
		"lookup":           LookupFunc,
		"lower":            stdlib.LowerFunc,
		"map":              MapFunc,
		"matchkeys":        MatchkeysFunc,
		"max":              stdlib.MaxFunc,
		"md5":              Md5Func,
		"merge":            stdlib.MergeFunc,
		"min":              stdlib.MinFunc,
		"one":              OneFunc,
		"parseint":         stdlib.ParseIntFunc,
		"pathexpand":       PathExpandFunc,
		"pow":              stdlib.PowFunc,
		"range":            stdlib.RangeFunc,
		"regex":            stdlib.RegexFunc,
		"regexall":         stdlib.RegexAllFunc,
		"replace":          ReplaceFunc,
		"reverse":          stdlib.ReverseListFunc,
		"rsadecrypt":       RsaDecryptFunc,
		"sensitive":        SensitiveFunc,
		"nonsensitive":     NonsensitiveFunc,
		"issensitive":      IssensitiveFunc,
		"setintersection":  stdlib.SetIntersectionFunc,
		"setproduct":       stdlib.SetProductFunc,
		"setsubtract":      stdlib.SetSubtractFunc,
		"setunion":         stdlib.SetUnionFunc,
		"sha1":             Sha1Func,
		"sha256":           Sha256Func,
		"sha512":           Sha512Func,
		"signum":           stdlib.SignumFunc,
		"slice":            stdlib.SliceFunc,
		"sort":             stdlib.SortFunc,
		"split":            stdlib.SplitFunc,
		"startswith":       StartsWithFunc,
		"strcontains":      StrContainsFunc,
		"strrev":           stdlib.ReverseFunc,
		"substr":           stdlib.SubstrFunc,
		"sum":              SumFunc,
		"textdecodebase64": TextDecodeBase64Func,
		"textencodebase64": TextEncodeBase64Func,
		"timestamp":        TimestampFunc,
		"timeadd":          stdlib.TimeAddFunc,
		"timecmp":          TimeCmpFunc,
		"title":            stdlib.TitleFunc,
		"tostring":         MakeToFunc(cty.String),
		"tonumber":         MakeToFunc(cty.Number),
		"tobool":           MakeToFunc(cty.Bool),
		"toset":            MakeToFunc(cty.Set(cty.DynamicPseudoType)),
		"tolist":           MakeToFunc(cty.List(cty.DynamicPseudoType)),
		"tomap":            MakeToFunc(cty.Map(cty.DynamicPseudoType)),
		"transpose":        TransposeFunc,
		"trim":             stdlib.TrimFunc,
		"trimprefix":       stdlib.TrimPrefixFunc,
		"trimspace":        stdlib.TrimSpaceFunc,
		"trimsuffix":       stdlib.TrimSuffixFunc,
		"try":              tryfunc.TryFunc,
		"upper":            stdlib.UpperFunc,
		"urlencode":        URLEncodeFunc,
		"uuid":             UUIDFunc,
		"uuidv5":           UUIDV5Func,
		"values":           stdlib.ValuesFunc,
		"yamldecode":       ctyyaml.YAMLDecodeFunc,
		"yamlencode":       ctyyaml.YAMLEncodeFunc,
		"zipmap":           stdlib.ZipmapFunc,
	}

}
