name: trivy triage
on:
  discussion:
    types: [created]
  workflow_dispatch:
    inputs:
      discussion_num:
        required: true
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/trivy-triage
        with:
          discussion_num: ${{ github.event.inputs.discussion_num }}
