FROM alpine:3.17.0
RUN apk --no-cache add ca-certificates git && \
    addgroup -S trivy && adduser -S trivy -G trivy
# binaries were created with GoReleaser
# need to copy binaries from folder with correct architecture
# example architecture folder: dist/trivy_canary_build_linux_arm64/trivy
ARG TARGETARCH
COPY "dist/trivy_canary_build_linux_${TARGETARCH}/trivy" /usr/local/bin/trivy
COPY contrib/*.tpl contrib/

USER trivy
ENTRYPOINT ["trivy"]
