FROM alpine:3.16.2
RUN apk --no-cache add ca-certificates git && \
    adduser -g "trivy" trivy

# binaries were created with GoReleaser
# need to copy binaries from folder with correct architecture
# example architecture folder: dist/trivy_canary_build_linux_arm64/trivy
ARG TARGETARCH
COPY "dist/trivy_canary_build_linux_${TARGETARCH}/trivy" /usr/local/bin/trivy
COPY contrib/*.tpl contrib/

USER trivy
ENTRYPOINT ["trivy"]
