<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.unrelated</groupId>
    <artifactId>parent</artifactId>
    <version>9.9.9</version>
    <packaging>pom</packaging>

    <dependencies>
        <dependency>
            <groupId>org.phantom</groupId>
            <artifactId>phantom-lib</artifactId>
            <version>6.6.6</version>
        </dependency>
    </dependencies>
</project>
