// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package operation

import (
	db2 "github.com/aquasecurity/trivy-db/pkg/db"
	"github.com/aquasecurity/trivy/pkg/db"
	"github.com/aquasecurity/trivy/pkg/github"
	"k8s.io/utils/clock"
)

// Injectors from inject.go:

func initializeDBClient() db.Client {
	config := db2.Config{}
	client := github.NewClient()
	realClock := clock.RealClock{}
	dbClient := db.NewClient(config, client, realClock)
	return dbClient
}
