labels: ["kind/feature"]
body:
  - type: markdown
    attributes:
      value: |
        #### Note
        Feel free to share your idea.
        Please ensure that you're not creating a duplicate ticket by searching the [issues](https://github.com/aquasecurity/trivy/issues)/[discussions](https://github.com/aquasecurity/trivy/discussions) beforehand.
        
        **Do not open a GitHub issue, please.** Maintainers triage discussions and then create issues.
        
        Please also check [our contribution guidelines](https://trivy.dev/latest/community/contribute/discussion/).
  - type: textarea
    attributes:
      label: Description
      description: Describe your idea.
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Target
      description: Which target is your idea related to?
      options:
        - Container Image
        - Filesystem
        - Git Repository
        - Virtual Machine Image
        - Kubernetes
        - AWS
        - SBOM
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Scanner
      description: Which scanner is your idea related to?
      options:
        - Vulnerability
        - Misconfiguration
        - Secret
        - License
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        We would be happy if you could share how you are using Trivy [here](https://github.com/aquasecurity/trivy/discussions/new?category=adopters).
