labels: ["triage/support"]
body:
  - type: markdown
    attributes:
      value: |
        #### Note
        If you have any troubles/questions, feel free to ask.
        Please ensure that you're not asking a duplicate question by searching the [issues](https://github.com/aquasecurity/trivy/issues)/[discussions](https://github.com/aquasecurity/trivy/discussions) beforehand.
        
        **Do not open a GitHub issue, please.** Maintainers triage discussions and then create issues.
        
        Please also check [our contribution guidelines](https://aquasecurity.github.io/trivy/latest/community/contribute/discussion/).
  - type: textarea
    attributes:
      label: Question
      description: What kind of problem are you facing? Or, what questions do you have?
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Target
      description: Which target are you scanning? It is equal to which subcommand you are using.
      options:
        - Container Image
        - Filesystem
        - Git Repository
        - Virtual Machine Image
        - Kubernetes
        - AWS
        - SBOM
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Scanner
      description: Which scanner are you using?
      options:
        - Vulnerability
        - Misconfiguration
        - Secret
        - License
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Output Format
      description: Which output format are you using?
      options:
        - Table
        - JSON
        - Template
        - SARIF
        - CycloneDX
        - SPDX
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Mode
      description: Which mode are you using? Specify "Standalone" if you are not using `trivy server`.
      options:
        - Standalone
        - Client/Server
    validations:
      required: false
  - type: input
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: "Example: macOS Big Sur"
    validations:
      required: false
  - type: textarea
    attributes:
      label: Version
      description: Output of `trivy --version`
      placeholder: "$ trivy --version"
      render: bash
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        We would be happy if you could share how you are using Trivy [here](https://github.com/aquasecurity/trivy/discussions/new?category=show-and-tell).
