title: "<company name> "
labels: ["adopters"]
body:
  - type: textarea
    id: links
    attributes:
      label: Share Links
      description: "If you would like to share a link to your project or company, please paste it below 🌐"
      value: |
        ...
    validations:
      required: false
  - type: textarea
    id: logo
    attributes:
      label: Share Logo
      description: "If you have a link to your logo, please provide it in the following text-box 🌐"
      value: |
        ...
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Please select all the scan targets that you are using
      options:
        - label: Container Images
        - label: Filesystem
        - label: Git Repository
        - label: Virtual Machine Images
        - label: Kubernetes
        - label: AWS
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Which scanners are you using on those scan targets?
      options:
        - label: OS packages and software dependencies in use (SBOM)
        - label: Known vulnerabilities (CVEs)
        - label: IaC issues and misconfigurations
        - label: Sensitive information and secrets
        - label: Software licenses
    validations:
      required: false
  - type: markdown
    id: more
    attributes:
      label: description
      description: "Please tell us more about your use case of Trivy -- anything that you would like to share 🎉"
      value: |
        ...
    validations:
      required: false