// Code generated by mockery v1.0.0. DO NOT EDIT.

package local

import mock "github.com/stretchr/testify/mock"
import types "github.com/aquasecurity/fanal/types"

// MockApplier is an autogenerated mock type for the Applier type
type MockApplier struct {
	mock.Mock
}

type ApplyLayersArgs struct {
	LayerIDs         []string
	LayerIDsAnything bool
}

type ApplyLayersReturns struct {
	Detail types.ImageDetail
	Err    error
}

type ApplyLayersExpectation struct {
	Args    ApplyLayersArgs
	Returns ApplyLayersReturns
}

func (_m *MockApplier) ApplyApplyLayersExpectation(e ApplyLayersExpectation) {
	var args []interface{}
	if e.Args.LayerIDsAnything {
		args = append(args, mock.Anything)
	} else {
		args = append(args, e.Args.LayerIDs)
	}
	_m.On("ApplyLayers", args...).Return(e.Returns.Detail, e.Returns.Err)
}

func (_m *MockApplier) ApplyApplyLayersExpectations(expectations []ApplyLayersExpectation) {
	for _, e := range expectations {
		_m.ApplyApplyLayersExpectation(e)
	}
}

// ApplyLayers provides a mock function with given fields: layerIDs
func (_m *MockApplier) ApplyLayers(layerIDs []string) (types.ImageDetail, error) {
	ret := _m.Called(layerIDs)

	var r0 types.ImageDetail
	if rf, ok := ret.Get(0).(func([]string) types.ImageDetail); ok {
		r0 = rf(layerIDs)
	} else {
		r0 = ret.Get(0).(types.ImageDetail)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]string) error); ok {
		r1 = rf(layerIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
