{
  "SchemaVersion": 2,
  "ArtifactName": "testdata/fixtures/fs/custom-policy",
  "ArtifactType": "filesystem",
  "Metadata": {
    "ImageConfig": {
      "architecture": "",
      "created": "0001-01-01T00:00:00Z",
      "os": "",
      "rootfs": {
        "type": "",
        "diff_ids": null
      },
      "config": {}
    }
  },
  "Results": [
    {
      "Target": "Dockerfile",
      "Class": "config",
      "Type": "dockerfile",
      "MisconfSummary": {
        "Successes": 25,
        "Failures": 2,
        "Exceptions": 0
      },
      "Misconfigurations": [
        {
          "Type": "Dockerfile Security Check",
          "ID": "N/A",
          "Title": "N/A",
          "Description": "Rego module: data.user.bar",
          "Message": "something bad: bar",
          "Namespace": "user.bar",
          "Query": "data.user.bar.deny",
          "Severity": "UNKNOWN",
          "Status": "FAIL",
          "Layer": {},
          "CauseMetadata": {
            "Provider": "Generic",
            "Service": "general",
            "Code": {
              "Lines": null
            }
          }
        },
        {
          "Type": "Dockerfile Security Check",
          "ID": "N/A",
          "Title": "N/A",
          "Description": "Rego module: data.user.foo",
          "Message": "something bad: foo",
          "Namespace": "user.foo",
          "Query": "data.user.foo.deny",
          "Severity": "UNKNOWN",
          "Status": "FAIL",
          "Layer": {},
          "CauseMetadata": {
            "Provider": "Generic",
            "Service": "general",
            "Code": {
              "Lines": null
            }
          }
        }
      ]
    }
  ]
}
