{
  "SchemaVersion": 2,
  "CreatedAt": "2021-08-25T12:20:30.000000005Z",
  "ArtifactName": "testdata/fixtures/repo/custom-policy",
  "ArtifactType": "repository",
  "Metadata": {
    "ImageConfig": {
      "architecture": "",
      "created": "0001-01-01T00:00:00Z",
      "os": "",
      "rootfs": {
        "type": "",
        "diff_ids": null
      },
      "config": {}
    }
  },
  "Results": [
    {
      "Target": "Dockerfile",
      "Class": "config",
      "Type": "dockerfile",
      "MisconfSummary": {
        "Successes": 28,
        "Failures": 2
      },
      "Misconfigurations": [
        {
          "Type": "Dockerfile Security Check",
          "ID": "AVD-BAR-0001",
          "AVDID": "AVD-BAR-0001",
          "Title": "Custom policy",
          "Description": "Custom policy for testing",
          "Message": "something bad: bar",
          "Namespace": "user.bar",
          "Query": "data.user.bar.deny",
          "Resolution": "Custom policy for testing",
          "Severity": "LOW",
          "Status": "FAIL",
          "Layer": {},
          "CauseMetadata": {
            "Provider": "Custom",
            "Service": "custom",
            "Code": {
              "Lines": null
            },
            "RenderedCause": {}
          }
        },
        {
          "Type": "Dockerfile Security Check",
          "ID": "AVD-FOO-0001",
          "AVDID": "AVD-FOO-0001",
          "Title": "Custom policy",
          "Description": "Custom policy for testing",
          "Message": "something bad: foo",
          "Namespace": "user.foo",
          "Query": "data.user.foo.deny",
          "Resolution": "Custom policy for testing",
          "Severity": "LOW",
          "Status": "FAIL",
          "Layer": {},
          "CauseMetadata": {
            "Provider": "Custom",
            "Service": "custom",
            "Code": {
              "Lines": null
            },
            "RenderedCause": {}
          }
        }
      ]
    }
  ]
}