[
  {
    "Target": "Dockerfile",
    "Class": "config",
    "Type": "dockerfile",
    "MisconfSummary": {
      "Successes": 0,
      "Failures": 0,
      "Exceptions": 1
    },
    "Misconfigurations": [
      {
        "Type": "Dockerfile Security Check",
        "ID": "DS002",
        "Title": "Image user should not be 'root'",
        "Description": "It is a good practice to run the container as a non-root user.",
        "Message": "data.appshield.dockerfile.DS002.exception[_][_] == \"\"",
        "Namespace": "appshield.dockerfile.DS002",
        "Query": "data.appshield.dockerfile.DS002.exception[_][_] == \"\"",
        "Resolution": "Add 'USER \u003cnon root user name\u003e' line to the Dockerfile",
        "Severity": "HIGH",
        "PrimaryURL": "https://avd.aquasec.com/appshield/ds002",
        "References": [
          "https://avd.aquasec.com/appshield/ds002"
        ],
        "Status": "EXCEPTION",
        "Layer": {
          "DiffID": "sha256:64e08a0c018f952137507c955f968f064c36171fb82229bb91802de44fb420ec"
        }
      }
    ]
  }
]