name: Deploy the dev documentation
on:
  push:
    paths:
      - 'docs/**'
      - mkdocs.yml
    branches:
      - main
jobs:
  deploy:
    name: Deploy the dev documentation
    runs-on: ubuntu-2404-2core
    steps:
      - name: Checkout main
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: true
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r docs/build/requirements.txt
      - name: Configure the git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Deploy the dev documents
        run: mike deploy --push dev
