name: Backport PR Check

on:
  pull_request:
    branches:
      - 'release/v*'

jobs:
  check-pr-author:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR author
        id: check_author
        env:
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
        run: |
          if [ "$PR_AUTHOR" != "aqua-bot" ]; then
            echo "::error::This branch is intended for automated backporting by bot. Please refer to the documentation:"
            echo "::error::https://trivy.dev/latest/community/maintainer/backporting/"
            exit 1
          fi